spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ryuzy_high?TNS_ADMIN=D:/Ryuzy/Spring/resource/Wallet_ryuzy
    username: admin
    password: Flyhigh4861*